export const symptomsList = [
  "Abasia",
  "Abdomen",
  "Aborto",
  "Absceso o Empiema",
  "Aburrimiento",
  "Accidente",
  "Accidente Cerebrovascular (ACV)",
  "Acidosis",
  "Acné",
  "Acromegalia",
  "Acroqueratosis",
  "Acúfeno",
  "Addison",
  "Adenitis",
  "Adenoides",
  "Adenopatía",
  "Adherencia",
  "Adormecimiento",
  "Adulto Mayor",
  "Aerofagia",
  "Afasia",
  "Afonía",
  "Afta",
  "Agitación",
  "Agorafobia",
  "Agotamiento (Burnout)",
  "Agresividad",
  "Agujetas",
  "Ahogos",
  "Alcoholismo",
  "Alergia: Fiebre del Heno",
  "Alergia: Lácteos",
  "Alergia: Picaduras",
  "Alergia: Plumas",
  "Alergia: Animales",
  "Alergia: Antibióticos",
  "Alergia: Caballos",
  "Alergia: Fresones",
  "Alergia: Gatos",
  "Alergia: Mariscos/Peces",
  "Alergia: Perros",
  "Alergia: Cacahuete",
  "Alergia: Polen",
  "Alergia: Polvo",
  "Alergias (General)",
  "Alexia Congénita",
  "Aliento (Mal)",
  "Alopecia",
  "Alucinaciones",
  "Alzheimer",
  "Ampolla",
  "Amputación",
  "Amígdalas",
  "Anemia",
  "Aneurisma",
  "Angina",
  "Angina de Pecho",
  "Angioma",
  "Angustia",
  "Ano",
  "Anorexia",
  "Anorgasmia",
  "Anosmia",
  "Antrax",
  "Anuria",
  "Apatía",
  "Apendicitis",
  "Apetito (Pérdida)",
  "Apoplejía",
  "Arritmia",
  "Arterias",
  "Arteriosclerosis",
  "Articulaciones",
  "Artritis",
  "Artrosis",
  "Asfixia",
  "Asma",
  "Astigmatismo",
  "Ataxia",
  "Atelectasia",
  "Autismo",
  "Autoinmune (Enfermedad)",
  "Azúcar",
  "Boca",
  "Boca: Encías",
  "Boca: Lengua",
  "Boca: Paladar",
  "Bocio",
  "Bolas en el cuerpo",
  "Borrachera",
  "Brazo",
  "Bronconeumonía",
  "Bronquios (Bronquitis)",
  "Bruxismo",
  "Bulimia",
  "Bursitis",
  "Cabeza: Dolores",
  "Cabeza: Cefaleas",
  "Cabeza: Migraña",
  "Caderas",
  "Calambre",
  "Calcio (Falta)",
  "Calvicie",
  "Callos",
  "Calor (Sofocos)",
  "Cáncer",
  "Cáncer de Huesos",
  "Cáncer de Lengua",
  "Cáncer de Piel",
  "Cáncer de Mamas",
  "Cáncer de Útero",
  "Candidiasis",
  "Cansancio (Fatiga)",
  "Cara",
  "Carbunco",
  "Cardias",
  "Caries Dentales",
  "Cartílago",
  "Caspa",
  "Cataratas",
  "Catarro",
  "Celulitis",
  "Cerebelo",
  "Cerebro",
  "Cerebro (Tumor)",
  "Ciática",
  "Cicatrización",
  "Ciego",
  "Cifosis",
  "Cigarrillo",
  "Circulación Sanguínea",
  "Cirrosis",
  "Cistitis",
  "Claustrofobia",
  "Clavícula",
  "Codos",
  "Colesterol",
  "Colitis",
  "Colon (Intestino Grueso)",
  "Coma",
  "Comezón",
  "Complejo de Inferioridad",
  "Conjuntivitis",
  "Constipación",
  "Contrariedad",
  "Convulsiones",
  "Corazón",
  "Corazón: Infarto",
  "Corazón: Taquicardia",
  "Coriza",
  "Córnea",
  "Costillas",
  "Coxis",
  "Cráneo",
  "Cuello",
  "Cuello del Útero",
  "Cuerpo (Lado Derecho)",
  "Cuerpo (Lado Izquierdo)",
  "Culebrilla (Herpes Zóster)",
  "Culpa",
  "Cutis",
  "Daltonismo",
  "Dedo Gordo del Pie",
  "Dedos",
  "Delgadez",
  "Delirium Tremens",
  "Demencia Senil",
  "Dengue",
  "Dentición",
  "Depresión",
  "Dermatitis",
  "Dermis",
  "Desmayo",
  "Desnutrición",
  "Diabetes",
  "Diarrea",
  "Dientes",
  "Dientes (Dolor)",
  "Digestión",
  "Disco (Hernia)",
  "Dislexia",
  "Dismenorrea",
  "Disentería",
  "Dispepsia",
  "Distrofia Muscular",
  "Divieso",
  "Dolor",
  "Dolores Migratorios",
  "Dorsal (Espina)",
  "Droga (Adicción)",
  "Duodeno",
  "Eczema",
  "Edema",
  "Embarazo",
  "Embolia",
  "Emociones (Bloqueo)",
  "Encéfalo",
  "Encías",
  "Endometriosis",
  "Enanismo",
  "Enfermedad de Crohn",
  "Enfermedades Crónicas",
  "Enfermedades Hereditarias",
  "Enfermedades Infantiles",
  "Enfermedades Mentales",
  "Enfermedades Venéreas",
  "Enfisema Pulmonar",
  "Enfriamiento",
  "Entumecimiento",
  "Enuresis",
  "Envejecimiento",
  "Epilepsia",
  "Equilibrio (Falta)",
  "Eructos",
  "Escalofríos",
  "Escamas",
  "Escarlatina",
  "Esclerodermia",
  "Esclerosis Múltiple",
  "Esclerosis Lateral Amiotrófica (ELA)",
  "Escoliosis",
  "Esguince",
  "Esófago",
  "Espalda",
  "Espasmofilia",
  "Espasmos",
  "Espinilla",
  "Espondilitis Anquilosante",
  "Espolón",
  "Estado de Ánimo",
  "Esterilidad",
  "Estómago",
  "Estómago (Ardores)",
  "Estrabismo",
  "Estrés",
  "Estreñimiento",
  "Eutanasia",
  "Exantema",
  "Extremidades Frías",
  "Falta de Apetito",
  "Faringitis",
  "Fatiga Crónica",
  "Fémur",
  "Fibroma",
  "Fibromialgia",
  "Fibrosis Quística",
  "Fiebre",
  "Fítula",
  "Flato",
  "Flebitis",
  "Flemas",
  "Fobias",
  "Forúnculo",
  "Fractura",
  "Frigidez",
  "Frío",
  "Gangrena",
  "Ganglios Linfáticos",
  "Garganta",
  "Gases",
  "Gastritis",
  "Gemelos",
  "Genitales",
  "Gingivitis",
  "Glaucoma",
  "Glándulas",
  "Glándulas Suprarrenales",
  "Globo Ocular",
  "Glóbulos Blancos",
  "Glóbulos Rojos",
  "Golpe",
  "Gota",
  "Grasa",
  "Gripe",
  "Halitosis",
  "Hemorragia",
  "Hemorroides",
  "Hepatitis",
  "Herida",
  "Hernia",
  "Hernia de Hiato",
  "Hernia Discal",
  "Hernia Inguinal",
  "Hernia Umbilical",
  "Herpes",
  "Herpes Genital",
  "Herpes Labial",
  "Hidropesía",
  "Hígado",
  "Hiperactividad",
  "Hipermetropía",
  "Hipertensión",
  "Hipertiroidismo",
  "Hipoglucemia",
  "Hipófisis",
  "Hipotensión",
  "Hipotálamo",
  "Hipotiroidismo",
  "Histeria",
  "Hombros",
  "Homosexualidad",
  "Hongos",
  "Hormonas",
  "Huesos",
  "Humedad",
  "Ictericia",
  "Ideas Suicidas",
  "Idiopatía",
  "Impaciencia",
  "Impotencia",
  "Incontinencia",
  "Indigestión",
  "Infección",
  "Infección Urinaria",
  "Infertilidad",
  "Inflamación",
  "Influenza",
  "Insomnio",
  "Insuficiencia Renal",
  "Insulina",
  "Intestino Delgado",
  "Intestino Grueso",
  "Intoxicación",
  "Ira",
  "Juanete",
  "Labios",
  "Laringitis",
  "Lengua",
  "Lepra",
  "Leucemia",
  "Leucorrea",
  "Linfático (Sistema)",
  "Lipoma",
  "Líquido (Retención)",
  "Lumbago",
  "Lunares",
  "Lupus",
  "Llagas",
  "Llanto",
  "Maculopatía",
  "Madre (Relación)",
  "Mal de Ojo",
  "Malformación",
  "Mamas (Senos)",
  "Manchas en la Piel",
  "Mandíbula",
  "Manos",
  "Mareos",
  "Matriz",
  "Médula Espinal",
  "Médula Ósea",
  "Melancolía",
  "Melanoma",
  "Memoria (Pérdida)",
  "Meningitis",
  "Menopausia",
  "Menstruación",
  "Mente",
  "Metabolismo",
  "Miedo",
  "Mielitis",
  "Miembro Fantasma",
  "Migraña",
  "Miopía",
  "Moco/Mucosidad",
  "Mononucleosis",
  "Morderse las Uñas",
  "Muerte",
  "Muñeca",
  "Músculos",
  "Muslos",
  "Nariz",
  "Nariz (Hemorragia)",
  "Naturaleza",
  "Náuseas",
  "Nervio Ciático",
  "Nervios",
  "Neumonía",
  "Neuralgia",
  "Neurastenía",
  "Neurosis",
  "Niñez",
  "Nódulos",
  "Nuca",
  "Obesidad",
  "Obsesión",
  "Oclusión Intestinal",
  "Odio",
  "Oídos",
  "Oídos: Zumbidos",
  "Ojos",
  "Ojos: Astigmatismo",
  "Ojos: Cataratas",
  "Ojos: Conjuntivitis",
  "Ojos: Estrabismo",
  "Ojos: Glaucoma",
  "Ojos: Hipermetropía",
  "Ojos: Miopía",
  "Ojos: Orzuelo",
  "Ojos: Presbicia",
  "Ojos: Sequedad",
  "Olvido",
  "Ombligo",
  "Hombros",
  "Omóplato",
  "Onicofagia",
  "Orejas",
  "Orgullo",
  "Orina",
  "Orzuelo",
  "Osteoporosis",
  "Otitis",
  "Ovarios",
  "Paciente",
  "Padre (Relación)",
  "Paladar",
  "Palpitaciones",
  "Panadizo",
  "Páncreas",
  "Pánico",
  "Paperas",
  "Parálisis",
  "Parálisis Facial",
  "Paranoia",
  "Parásitos",
  "Parkinson",
  "Párpados",
  "Parto",
  "Pechos",
  "Pelo (Caída)",
  "Pelvis",
  "Pene",
  "Pensamientos",
  "Perdón",
  "Pericarditis",
  "Peritonitis",
  "Pesadilla",
  "Peso (Exceso)",
  "Pestañas",
  "Pezones",
  "Picaduras",
  "Pie de Atleta",
  "Piel",
  "Piel: Acné",
  "Piel: Cáncer",
  "Piel: Eczemas",
  "Piel: Psoriasis",
  "Piel: Urticaria",
  "Piel: Verrugas",
  "Piel: Vitíligo",
  "Piernas",
  "Piernas: Varices",
  "Pies",
  "Piojos",
  "Plaquetas",
  "Pleura",
  "Plexo Solar",
  "Pólipo",
  "Polio",
  "Polen",
  "Polvo",
  "Presión Arterial",
  "Próstata",
  "Psoriasis",
  "Pulgar",
  "Pulmones",
  "Punta de Costado",
  "Quemadura",
  "Quiste",
  "Quiste Ovárico",
  "Rabia",
  "Raquitismo",
  "Recto",
  "Regulación Térmica",
  "Rechazo",
  "Regla",
  "Resentimiento",
  "Resfriado",
  "Respiración",
  "Reuma",
  "Riñones",
  "Rodillas",
  "Ronquidos",
  "Rosácea",
  "Rostro",
  "Rótula",
  "Rubéola",
  "Sacro",
  "Saliva",
  "Salpullido",
  "Sangre",
  "Sangre: Anemia",
  "Sangre: Circulación",
  "Sangre: Diabetes",
  "Sangre: Hemorragia",
  "Sangre: Hipertensión",
  "Sangre: Hipoglucemia",
  "Sangre: Leucemia",
  "Sarampión",
  "Sarna",
  "Seborrea",
  "Sed",
  "Senilidad",
  "Seno",
  "Sequedad",
  "Sexualidad",
  "Sida",
  "Sífilis",
  "Síndrome de Down",
  "Sinusitis",
  "Sofocos",
  "Sordera",
  "Sueño",
  "Suicidio",
  "Suprarrenales",
  "Tabaquismo",
  "Talla Baja",
  "Taquicardia",
  "Tartamudez",
  "Tejidos",
  "Tendinitis",
  "Tendones",
  "Tensión Arterial",
  "Testículos",
  "Tétanos",
  "Tics",
  "Timidez",
  "Timo",
  "Tiroides",
  "Tobillos",
  "TOC",
  "Tortícolis",
  "Tos",
  "Toxicomanía",
  "Trabajo de Parto",
  "Tráquea",
  "Trastornos Menstruales",
  "Traumatismo",
  "Trigémino",
  "Tristeza",
  "Trombosis",
  "Tuberculosis",
  "Tumor",
  "Túnel Carpiano",
  "Úlcera",
  "Úlcera Gástrica",
  "Umbilical (Hernia)",
  "Uñas",
  "Uñas: Comerse",
  "Uñas Amarillas",
  "Uñas Blandas",
  "Uñero",
  "Uremia",
  "Ureteritis",
  "Uretra",
  "Uretritis",
  "Urticaria",
  "Útero",
  "Vagina",
  "Vagina: Herpes",
  "Vaginitis",
  "Varicela",
  "Varices",
  "Vegetaciones",
  "Vegetativo",
  "Vejiga",
  "Vejiga (Cistitis)",
  "Venas",
  "Venas (Varices)",
  "Venéreas",
  "Verrugas",
  "Vértebras",
  "Vértigo",
  "Vesícula Biliar",
  "Vientre",
  "Violación",
  "Viruelas",
  "Virus",
  "Vista",
  "Vitíligo",
  "Vómito de Sangre",
  "Vómitos",
  "Voz",
  "Voz (Pérdida)",
  "Xerostomía",
  "Zona",
  "Zumbidos",
  "Zurdo"
];